### ISSUE TITLE
does it work with maps or non-traditional SCSS vars?

### ISSUE THREAD

**Issue by iamnewton** [subsetcss/linter#5]
I have a deep map of variables that get called as such:

```
padding: map-deep-get($theme, spacers, half) map-deep-get($theme, spacers, 1);
```

and I'm wondering if this will work with stuff like that?

**Comment by knownasilya** [comment]
Yup, you can specify any string, including custom values like you have above.

**Comment by iamnewton** [comment]
so if i want to pass options, then pass it as the `function` (e.g. map-deep-get...) rather than passing the actual value?

**Comment by iamnewton** [comment]
```
#10957: $ npm run lint:css

> lint:css /components
> stylelint src/**/*.scss

TypeError: Cannot read property 'forEach' of undefined
    at /components/src/alert/_index.scss:14:2
    at postcssRoot.walkAtRules.rule (/components/node_modules/subsetcss/dist/subsetcss.cjs.development.js:58:36)
    at /components/node_modules/postcss/lib/container.js:295:18
    at /components/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/components/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/components/node_modules/postcss/lib/container.js:131:17)
    at /components/node_modules/postcss/lib/container.js:148:24
    at Root.each (/components/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/components/node_modules/postcss/lib/container.js:131:17)
    at Root.walkAtRules (components/node_modules/postcss/lib/container.js:293:19)
    at /components/node_modules/subsetcss/dist/subsetcss.cjs.development.js:51:21
```

**Comment by knownasilya** [comment]
Ah, I see. That is not possible yet, but I'm open to open to adding it.

**Comment by knownasilya** [comment]
How would you expect arguments to work for a function of this sort?

**Comment by iamnewton** [comment]
```
module.exports = {
    'subsets': {
       'z-index': [
            'map-deep-get($theme, typography, zindex, negative)',
            'map-deep-get($theme, typography, zindex, base)',
            'map-deep-get($theme, typography, zindex, \'dropdown-bg\')',
            'map-deep-get($theme, typography, zindex, dropdown)',
            'map-deep-get($theme, typography, zindex, fixed)',
            'map-deep-get($theme, typography, zindex, sticky)',
            'map-deep-get($theme, typography, zindex, \'modal-bg\')',
            'map-deep-get($theme, typography, zindex, modal)',
            'map-deep-get($theme, typography, zindex, popover)',
            'map-deep-get($theme, typography, zindex, tooltip)'
        ]
    }
};
```

I'm fine with passing it like this since its the actual value that is passed in.

**Comment by knownasilya** [comment]
Yes, that is the preferred method. I thought maybe you needed something dynamic.

**Comment by iamnewton** [comment]
No rush, but just checking in for timeline on this feature?

**Comment by knownasilya** [comment]
Just for clarity, something like:

```js
module.exports = {
    'subsets': {
       'z-index': function(prop) {
        return [...];
      }
    }
};
```

**Comment by iamnewton** [comment]
yeah, I think so.

**Comment by knownasilya** [comment]
Try 0.2.3, see the changelog for changes.

**Comment by iamnewton** [comment]
Works really well, but how do you solve for this?

```
 50:3   ✖  Invalid `border-width: 0 map-deep-get($theme, border, width, sm)`. It should use one of the following values: 0, map-deep-get($theme, border, width, sm), map-deep-get($theme, border, width, md).
```

I've tried adding:

```js
'border-width': (key, value) => [
    0,
    'map-deep-get($theme, border, width, sm)',
    'map-deep-get($theme, border, width, md)',
],
```

and 

```
```js
'border-width': [
    0,
    'map-deep-get($theme, border, width, sm)',
    'map-deep-get($theme, border, width, md)',
],
```

**Comment by knownasilya** [comment]
@iamnewton unfortunately that case hasn't been handled yet, will be working on that this week.

**Comment by iamnewton** [comment]
K, cool.  What are the functions meant to accomplish/return?  Didn't see any docs about them.

**Comment by iamnewton** [comment]
So the idea is to dynamically create values, e.g. type measures?

**Comment by knownasilya** [comment]
@iamnewton pretty much, basically not to care how you come up with the resulting array of valid values.

**Comment by knownasilya** [comment]
Going to open a new issue for handling multi value props, closing this since it seems to have been covered.

**Comment by knownasilya** [comment]
https://github.com/subsetcss/linter/issues/8
